version: '3.7'

services:
    mssql:
        build:
            context: ./mssql
            dockerfile: Dockerfile
        container_name: dotnet-007-eximia-co-desafio-final
        ports:
            - 1433:1433
